name: Teams Notification
description: A Buildkite plugin for sending incoming webhook notifications setup on specific MS Teams channels.
author: https://github.com/buildkite-plugins
requirements:
  - bash
  - curl
configuration:
  properties:
    webhook_url:
      type: string
    message:
      type: string
    dry_run:
      type: boolean
  required:
    - webhook_url
    - message
  additionalProperties: false
