name: Teams Notification
description: A Buildkite plugin that allows sending incoming webhooks at the pre-exit job lifecycle event.
author: https://github.com/buildkite-plugins
requirements:
  - bash
  - curl
configuration:
  properties:
    webhook_url:
      type: string
    message:
      type: string
  required:
    - webhook_url
    - message
  additionalProperties: false
